name: Debugging Demo
#once the workflow fails due to exit 1, select Re-run failed jobs from github UI and enable the debug logging

on:
    workflow_dispatch:
    push:

env:
    USER_1: "foo-user"
    USER_2: "boo-user"

jobs:
    debug_job:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1- Checkout Repo
              uses: actions/checkout@v4
            - name: Step 2- Set User_1 as Username
              run: | #creating new variable called USERNAME using the environment 
                echo "USERNAME=$USER_1" >> $GITHUB_ENV
            - name: Step 3 - Printing username
              run: | #using exit 1 to fail the workflow and leave
                echo "Printing USERNAME env variable from previous step"  
                echo "Username ========== $USERNAME"
                exit 1 
            - name: Step 4- Printing USER_2
              run: |
                echo $USER_2

        